default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: no-commit-to-branch
        args:
          - "-b master"
          - "-b main"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: "^racoon_ai/proto_py/"

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: "^racoon_ai/proto_py/"

  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        exclude: "^racoon_ai/proto_py/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        exclude: "^racoon_ai/proto_py/"
        additional_dependencies:
          - "types-protobuf==3.18.2"

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        exclude: "^racoon_ai/proto_py/"
