default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: no-commit-to-branch
        args: [--branch, dev, --branch, master, --branch, main]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-file=pyproject.toml"

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - "--config=.flake8"

  - repo: https://github.com/pycqa/pylint
    rev: v2.13.5
    hooks:
      - id: pylint
        args:
          - "--rcfile=pyproject.toml"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args:
          - "--config-file=pyproject.toml"
        additional_dependencies:
          - "types-protobuf==3.18.2"

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - "--config=pyproject.toml"
