[tool.poetry]
name = "racoon-ai"
version = "0.0.1"
description = "Ri-one Accurate Operation AI"
authors = ["Ri-one-SSL <rionesslq@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10"
protobuf = "^3.19.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
