"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import grSim_Commands_pb2
import grSim_Replacement_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class grSim_Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COMMANDS_FIELD_NUMBER: builtins.int
    REPLACEMENT_FIELD_NUMBER: builtins.int
    @property
    def commands(self) -> grSim_Commands_pb2.grSim_Commands: ...
    @property
    def replacement(self) -> grSim_Replacement_pb2.grSim_Replacement: ...
    def __init__(self,
        *,
        commands : typing.Optional[grSim_Commands_pb2.grSim_Commands] = ...,
        replacement : typing.Optional[grSim_Replacement_pb2.grSim_Replacement] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commands",b"commands","replacement",b"replacement"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commands",b"commands","replacement",b"replacement"]) -> None: ...
global___grSim_Packet = grSim_Packet
