"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import ssl_vision_detection_pb2
import ssl_vision_geometry_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SSL_WrapperPacket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DETECTION_FIELD_NUMBER: builtins.int
    GEOMETRY_FIELD_NUMBER: builtins.int
    @property
    def detection(self) -> ssl_vision_detection_pb2.SSL_DetectionFrame: ...
    @property
    def geometry(self) -> ssl_vision_geometry_pb2.SSL_GeometryData: ...
    def __init__(self,
        *,
        detection : typing.Optional[ssl_vision_detection_pb2.SSL_DetectionFrame] = ...,
        geometry : typing.Optional[ssl_vision_geometry_pb2.SSL_GeometryData] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["detection",b"detection","geometry",b"geometry"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["detection",b"detection","geometry",b"geometry"]) -> None: ...
global___SSL_WrapperPacket = SSL_WrapperPacket
