"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_gc_common_pb2
import ssl_vision_geometry_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class RobotLimits(google.protobuf.message.Message):
    """Movement limits for a robot"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ACC_SPEEDUP_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    ACC_SPEEDUP_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    ACC_BRAKE_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    ACC_BRAKE_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    VEL_ABSOLUTE_MAX_FIELD_NUMBER: builtins.int
    VEL_ANGULAR_MAX_FIELD_NUMBER: builtins.int
    acc_speedup_absolute_max: builtins.float = ...
    """Max absolute speed-up acceleration [m/s^2]"""

    acc_speedup_angular_max: builtins.float = ...
    """Max angular speed-up acceleration [rad/s^2]"""

    acc_brake_absolute_max: builtins.float = ...
    """Max absolute brake acceleration [m/s^2]"""

    acc_brake_angular_max: builtins.float = ...
    """Max angular brake acceleration [rad/s^2]"""

    vel_absolute_max: builtins.float = ...
    """Max absolute velocity [m/s]"""

    vel_angular_max: builtins.float = ...
    """Max angular velocity [rad/s]"""

    def __init__(self,
        *,
        acc_speedup_absolute_max : typing.Optional[builtins.float] = ...,
        acc_speedup_angular_max : typing.Optional[builtins.float] = ...,
        acc_brake_absolute_max : typing.Optional[builtins.float] = ...,
        acc_brake_angular_max : typing.Optional[builtins.float] = ...,
        vel_absolute_max : typing.Optional[builtins.float] = ...,
        vel_angular_max : typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["acc_brake_absolute_max",b"acc_brake_absolute_max","acc_brake_angular_max",b"acc_brake_angular_max","acc_speedup_absolute_max",b"acc_speedup_absolute_max","acc_speedup_angular_max",b"acc_speedup_angular_max","vel_absolute_max",b"vel_absolute_max","vel_angular_max",b"vel_angular_max"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["acc_brake_absolute_max",b"acc_brake_absolute_max","acc_brake_angular_max",b"acc_brake_angular_max","acc_speedup_absolute_max",b"acc_speedup_absolute_max","acc_speedup_angular_max",b"acc_speedup_angular_max","vel_absolute_max",b"vel_absolute_max","vel_angular_max",b"vel_angular_max"]) -> None: ...
global___RobotLimits = RobotLimits

class RobotWheelAngles(google.protobuf.message.Message):
    """Robot wheel angle configuration
    all angles are relative to looking forward,
    all wheels / angles are clockwise
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FRONT_RIGHT_FIELD_NUMBER: builtins.int
    BACK_RIGHT_FIELD_NUMBER: builtins.int
    BACK_LEFT_FIELD_NUMBER: builtins.int
    FRONT_LEFT_FIELD_NUMBER: builtins.int
    front_right: builtins.float = ...
    """Angle front right [rad]"""

    back_right: builtins.float = ...
    """Angle back right [rad]"""

    back_left: builtins.float = ...
    """Angle back left [rad]"""

    front_left: builtins.float = ...
    """Angle front left [rad]"""

    def __init__(self,
        *,
        front_right : typing.Optional[builtins.float] = ...,
        back_right : typing.Optional[builtins.float] = ...,
        back_left : typing.Optional[builtins.float] = ...,
        front_left : typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["back_left",b"back_left","back_right",b"back_right","front_left",b"front_left","front_right",b"front_right"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["back_left",b"back_left","back_right",b"back_right","front_left",b"front_left","front_right",b"front_right"]) -> None: ...
global___RobotWheelAngles = RobotWheelAngles

class RobotSpecs(google.protobuf.message.Message):
    """Specs of a robot"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    RADIUS_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    MASS_FIELD_NUMBER: builtins.int
    MAX_LINEAR_KICK_SPEED_FIELD_NUMBER: builtins.int
    MAX_CHIP_KICK_SPEED_FIELD_NUMBER: builtins.int
    CENTER_TO_DRIBBLER_FIELD_NUMBER: builtins.int
    LIMITS_FIELD_NUMBER: builtins.int
    WHEEL_ANGLES_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> ssl_gc_common_pb2.RobotId:
        """Id of the robot"""
        pass
    radius: builtins.float = ...
    """Robot radius [m]"""

    height: builtins.float = ...
    """Robot height [m]"""

    mass: builtins.float = ...
    """Robot mass [kg]"""

    max_linear_kick_speed: builtins.float = ...
    """Max linear kick speed [m/s] (unset = unlimited)"""

    max_chip_kick_speed: builtins.float = ...
    """Max chip kick speed [m/s] (unset = unlimited)"""

    center_to_dribbler: builtins.float = ...
    """Distance from robot center to dribbler [m] (implicitly defines the opening angle and dribbler width)"""

    @property
    def limits(self) -> global___RobotLimits:
        """Movement limits"""
        pass
    @property
    def wheel_angles(self) -> global___RobotWheelAngles:
        """Wheel angle configuration"""
        pass
    @property
    def custom(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        """Custom robot spec for specific simulators (the protobuf files are managed by the simulators)"""
        pass
    def __init__(self,
        *,
        id : typing.Optional[ssl_gc_common_pb2.RobotId] = ...,
        radius : typing.Optional[builtins.float] = ...,
        height : typing.Optional[builtins.float] = ...,
        mass : typing.Optional[builtins.float] = ...,
        max_linear_kick_speed : typing.Optional[builtins.float] = ...,
        max_chip_kick_speed : typing.Optional[builtins.float] = ...,
        center_to_dribbler : typing.Optional[builtins.float] = ...,
        limits : typing.Optional[global___RobotLimits] = ...,
        wheel_angles : typing.Optional[global___RobotWheelAngles] = ...,
        custom : typing.Optional[typing.Iterable[google.protobuf.any_pb2.Any]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["center_to_dribbler",b"center_to_dribbler","height",b"height","id",b"id","limits",b"limits","mass",b"mass","max_chip_kick_speed",b"max_chip_kick_speed","max_linear_kick_speed",b"max_linear_kick_speed","radius",b"radius","wheel_angles",b"wheel_angles"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["center_to_dribbler",b"center_to_dribbler","custom",b"custom","height",b"height","id",b"id","limits",b"limits","mass",b"mass","max_chip_kick_speed",b"max_chip_kick_speed","max_linear_kick_speed",b"max_linear_kick_speed","radius",b"radius","wheel_angles",b"wheel_angles"]) -> None: ...
global___RobotSpecs = RobotSpecs

class RealismConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CUSTOM_FIELD_NUMBER: builtins.int
    @property
    def custom(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]:
        """Custom config for specific simulators (the protobuf files are managed by the simulators)"""
        pass
    def __init__(self,
        *,
        custom : typing.Optional[typing.Iterable[google.protobuf.any_pb2.Any]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["custom",b"custom"]) -> None: ...
global___RealismConfig = RealismConfig

class SimulatorConfig(google.protobuf.message.Message):
    """Change the simulator configuration"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    GEOMETRY_FIELD_NUMBER: builtins.int
    ROBOT_SPECS_FIELD_NUMBER: builtins.int
    REALISM_CONFIG_FIELD_NUMBER: builtins.int
    VISION_PORT_FIELD_NUMBER: builtins.int
    @property
    def geometry(self) -> ssl_vision_geometry_pb2.SSL_GeometryData:
        """Update the geometry"""
        pass
    @property
    def robot_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RobotSpecs]:
        """Update the robot specs"""
        pass
    @property
    def realism_config(self) -> global___RealismConfig:
        """Update realism configuration"""
        pass
    vision_port: builtins.int = ...
    """Change the vision publish port"""

    def __init__(self,
        *,
        geometry : typing.Optional[ssl_vision_geometry_pb2.SSL_GeometryData] = ...,
        robot_specs : typing.Optional[typing.Iterable[global___RobotSpecs]] = ...,
        realism_config : typing.Optional[global___RealismConfig] = ...,
        vision_port : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["geometry",b"geometry","realism_config",b"realism_config","vision_port",b"vision_port"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["geometry",b"geometry","realism_config",b"realism_config","robot_specs",b"robot_specs","vision_port",b"vision_port"]) -> None: ...
global___SimulatorConfig = SimulatorConfig
