"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_simulation_control_pb2
import ssl_simulation_robot_control_pb2
import ssl_simulation_robot_feedback_pb2
import ssl_vision_detection_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class SimulationSyncRequest(google.protobuf.message.Message):
    """Request from the team to the simulator"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SIM_STEP_FIELD_NUMBER: builtins.int
    SIMULATOR_COMMAND_FIELD_NUMBER: builtins.int
    ROBOT_CONTROL_FIELD_NUMBER: builtins.int
    sim_step: builtins.float = ...
    """The simulation step [s] to perform"""

    @property
    def simulator_command(self) -> ssl_simulation_control_pb2.SimulatorCommand:
        """An optional simulator command"""
        pass
    @property
    def robot_control(self) -> ssl_simulation_robot_control_pb2.RobotControl:
        """An optional robot control command"""
        pass
    def __init__(self,
        *,
        sim_step : typing.Optional[builtins.float] = ...,
        simulator_command : typing.Optional[ssl_simulation_control_pb2.SimulatorCommand] = ...,
        robot_control : typing.Optional[ssl_simulation_robot_control_pb2.RobotControl] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["robot_control",b"robot_control","sim_step",b"sim_step","simulator_command",b"simulator_command"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["robot_control",b"robot_control","sim_step",b"sim_step","simulator_command",b"simulator_command"]) -> None: ...
global___SimulationSyncRequest = SimulationSyncRequest

class SimulationSyncResponse(google.protobuf.message.Message):
    """Response to last SimulationSyncRequest"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DETECTION_FIELD_NUMBER: builtins.int
    ROBOT_CONTROL_RESPONSE_FIELD_NUMBER: builtins.int
    @property
    def detection(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ssl_vision_detection_pb2.SSL_DetectionFrame]:
        """List of detection frames for all cameras with the state after the simulation step in the request was performed"""
        pass
    @property
    def robot_control_response(self) -> ssl_simulation_robot_feedback_pb2.RobotControlResponse:
        """An optional robot control response"""
        pass
    def __init__(self,
        *,
        detection : typing.Optional[typing.Iterable[ssl_vision_detection_pb2.SSL_DetectionFrame]] = ...,
        robot_control_response : typing.Optional[ssl_simulation_robot_feedback_pb2.RobotControlResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["robot_control_response",b"robot_control_response"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["detection",b"detection","robot_control_response",b"robot_control_response"]) -> None: ...
global___SimulationSyncResponse = SimulationSyncResponse
