"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import ssl_gc_common_pb2
import ssl_simulation_config_pb2
import ssl_simulation_error_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TeleportBall(google.protobuf.message.Message):
    """Teleport the ball to a new location and optionally set it to some velocity"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    VX_FIELD_NUMBER: builtins.int
    VY_FIELD_NUMBER: builtins.int
    VZ_FIELD_NUMBER: builtins.int
    TELEPORT_SAFELY_FIELD_NUMBER: builtins.int
    ROLL_FIELD_NUMBER: builtins.int
    BY_FORCE_FIELD_NUMBER: builtins.int
    x: builtins.float = ...
    """x-coordinate [m]"""

    y: builtins.float = ...
    """y-coordinate [m]"""

    z: builtins.float = ...
    """z-coordinate (height) [m]"""

    vx: builtins.float = ...
    """Velocity in x-direction [m/s]"""

    vy: builtins.float = ...
    """Velocity in y-direction [m/s]"""

    vz: builtins.float = ...
    """Velocity in z-direction [m/s]"""

    teleport_safely: builtins.bool = ...
    """Teleport the ball safely to the target, for example by
    moving robots out of the way in case of collision and set speed of robots close-by to zero
    """

    roll: builtins.bool = ...
    """Adapt the angular ball velocity such that the ball is rolling"""

    by_force: builtins.bool = ...
    """Instead of teleporting the ball, apply some force to make sure
    the ball reaches the required position soon (velocity is ignored if true)
    WARNING: A command with by_force stays active (the move will take some time)
    until cancled by another TeleportBall command with by_force = false.
    To avoid teleporting the ball at the end and resetting its current spin,
    do not set any of the optional fields in this message to end the force without triggering
    an additional teleportation
    """

    def __init__(self,
        *,
        x : typing.Optional[builtins.float] = ...,
        y : typing.Optional[builtins.float] = ...,
        z : typing.Optional[builtins.float] = ...,
        vx : typing.Optional[builtins.float] = ...,
        vy : typing.Optional[builtins.float] = ...,
        vz : typing.Optional[builtins.float] = ...,
        teleport_safely : typing.Optional[builtins.bool] = ...,
        roll : typing.Optional[builtins.bool] = ...,
        by_force : typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["by_force",b"by_force","roll",b"roll","teleport_safely",b"teleport_safely","vx",b"vx","vy",b"vy","vz",b"vz","x",b"x","y",b"y","z",b"z"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["by_force",b"by_force","roll",b"roll","teleport_safely",b"teleport_safely","vx",b"vx","vy",b"vy","vz",b"vz","x",b"x","y",b"y","z",b"z"]) -> None: ...
global___TeleportBall = TeleportBall

class TeleportRobot(google.protobuf.message.Message):
    """Teleport a robot to some location and give it a velocity"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    ORIENTATION_FIELD_NUMBER: builtins.int
    V_X_FIELD_NUMBER: builtins.int
    V_Y_FIELD_NUMBER: builtins.int
    V_ANGULAR_FIELD_NUMBER: builtins.int
    PRESENT_FIELD_NUMBER: builtins.int
    BY_FORCE_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> ssl_gc_common_pb2.RobotId:
        """Robot id to teleport"""
        pass
    x: builtins.float = ...
    """x-coordinate [m]"""

    y: builtins.float = ...
    """y-coordinate [m]"""

    orientation: builtins.float = ...
    """Orientation [rad], measured from the x-axis counter-clockwise"""

    v_x: builtins.float = ...
    """Global velocity [m/s] towards x-axis"""

    v_y: builtins.float = ...
    """Global velocity [m/s] towards y-axis"""

    v_angular: builtins.float = ...
    """Angular velocity [rad/s]"""

    present: builtins.bool = ...
    """Robot should be present on the field?
    true -> robot will be added, if it does not exist yet
    false -> robot will be removed, if it is present
    """

    by_force: builtins.bool = ...
    """Instead of teleporting, apply some force to make sure
    the robot reaches the required position soon (velocity is ignored if true)
    WARNING: A command with by_force stays active (the move will take some time)
    until cancled by another TeleportRobot command for the same bot with by_force = false.
    To avoid teleporting at the end,
    do not set any of the optional fields in this message
    to end the force without triggering
    an additional teleportation
    """

    def __init__(self,
        *,
        id : typing.Optional[ssl_gc_common_pb2.RobotId] = ...,
        x : typing.Optional[builtins.float] = ...,
        y : typing.Optional[builtins.float] = ...,
        orientation : typing.Optional[builtins.float] = ...,
        v_x : typing.Optional[builtins.float] = ...,
        v_y : typing.Optional[builtins.float] = ...,
        v_angular : typing.Optional[builtins.float] = ...,
        present : typing.Optional[builtins.bool] = ...,
        by_force : typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["by_force",b"by_force","id",b"id","orientation",b"orientation","present",b"present","v_angular",b"v_angular","v_x",b"v_x","v_y",b"v_y","x",b"x","y",b"y"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["by_force",b"by_force","id",b"id","orientation",b"orientation","present",b"present","v_angular",b"v_angular","v_x",b"v_x","v_y",b"v_y","x",b"x","y",b"y"]) -> None: ...
global___TeleportRobot = TeleportRobot

class SimulatorControl(google.protobuf.message.Message):
    """Control the simulation"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TELEPORT_BALL_FIELD_NUMBER: builtins.int
    TELEPORT_ROBOT_FIELD_NUMBER: builtins.int
    SIMULATION_SPEED_FIELD_NUMBER: builtins.int
    @property
    def teleport_ball(self) -> global___TeleportBall:
        """Teleport the ball"""
        pass
    @property
    def teleport_robot(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TeleportRobot]:
        """Teleport robots"""
        pass
    simulation_speed: builtins.float = ...
    """Change the simulation speed"""

    def __init__(self,
        *,
        teleport_ball : typing.Optional[global___TeleportBall] = ...,
        teleport_robot : typing.Optional[typing.Iterable[global___TeleportRobot]] = ...,
        simulation_speed : typing.Optional[builtins.float] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["simulation_speed",b"simulation_speed","teleport_ball",b"teleport_ball"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["simulation_speed",b"simulation_speed","teleport_ball",b"teleport_ball","teleport_robot",b"teleport_robot"]) -> None: ...
global___SimulatorControl = SimulatorControl

class SimulatorCommand(google.protobuf.message.Message):
    """Command from the connected client to the simulator"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CONTROL_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    @property
    def control(self) -> global___SimulatorControl:
        """Control the simulation"""
        pass
    @property
    def config(self) -> ssl_simulation_config_pb2.SimulatorConfig:
        """Configure the simulation"""
        pass
    def __init__(self,
        *,
        control : typing.Optional[global___SimulatorControl] = ...,
        config : typing.Optional[ssl_simulation_config_pb2.SimulatorConfig] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["config",b"config","control",b"control"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["config",b"config","control",b"control"]) -> None: ...
global___SimulatorCommand = SimulatorCommand

class SimulatorResponse(google.protobuf.message.Message):
    """Response of the simulator to the connected client"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERRORS_FIELD_NUMBER: builtins.int
    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[ssl_simulation_error_pb2.SimulatorError]:
        """List of errors, like using unsupported features"""
        pass
    def __init__(self,
        *,
        errors : typing.Optional[typing.Iterable[ssl_simulation_error_pb2.SimulatorError]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["errors",b"errors"]) -> None: ...
global___SimulatorResponse = SimulatorResponse
